services:
  - type: web
    name: landing-page-be
    runtime: node
    plan: free
    rootDir: landing-page-be
    buildCommand: npm install --legacy-peer-deps --include=dev && npx prisma generate && npx nest build
    startCommand: npx prisma migrate deploy && node landing-page-be/dist/main
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: landing-page-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: FRONTEND_URL
        value: https://danisolation-landing-page.vercel.app
      - key: NODE_ENV
        value: production

databases:
  - name: landing-page-db
    plan: free
    databaseName: landing_page
    user: landing_page_user
